spring:
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false   # Se activa por perfil

server:
  port: 8080
  servlet:
    context-path: /

app:
  jwt:
    secret: ${JWT_SECRET:medical_platform_super_secret_key_change_in_production_32chars}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}   # 24h

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
