spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:QA}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:742742}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: false

app:
  jwt:
    secret: ${JWT_SECRET:medical_platform_local_secret_key_minimo_32_caracteres}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    com.medical: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
